# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 01:23
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('products', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
